# Generated by Django 3.2.8 on 2021-10-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Analysis',
            new_name='Gap',
        ),
    ]
