# Generated by Django 3.2.8 on 2021-10-08 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_rename_analysis_gap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gap',
            old_name='selected_date',
            new_name='date_selected',
        ),
    ]
